name: Current Monthly issue metrics
on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 1 * *'

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest

    steps:

    - name: Get dates for current month
      shell: bash
      run: |
        # Get the current date
        current_date=$(date +'%Y-%m-%d')

        # Extract the year and month from the current date
        year=$(date -d "$current_date" +'%Y')
        month=$(date -d "$current_date" +'%m')

        # Calculate the first day of the this month
        first_day=$(date -d "$year-$month-01" +'%Y-%m-%d')

        echo "$first_day..$current_date"
        echo "this_month=$first_day..$current_date" >> "$GITHUB_ENV"

    - name: Run issue-metrics tool
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:sachinphegde/ExtractStravaData is:issue created:${{ env.this_month }} -reason:"not planned"'

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Monthly issue metrics report
        content-filepath: ./issue_metrics.md
        assignees: <YOUR_GITHUB_HANDLE_HERE>
